### ISSUE TITLE
书签搜索不支持edge的内测版本

### ISSUE THREAD

**Issue by HaoTian22** [L1cardo/Edge-Helper-uTools#2]
在Edge的Beta版，Dev版，Canary版本中使用书签搜索，都会匹配到稳定版Edge中的书签内容
希望加个获取窗口路径之类的语句，判断路径中是否有Beta之类的字样，分开来获取，以免书签获取混乱（我不会JS所以不会改）

具体要更改的位置
![QQ截图20200706192726](https://user-images.githubusercontent.com/48882584/86588717-d109e700-bfbe-11ea-86d4-5ba13e9a4cf2.png)

**Comment by L1cardo** [comment]
抱歉我不懂 js，不太会改这个。。。
