### ISSUE TITLE
图标地址获取方法

### ISSUE THREAD

**Issue by ZhangTianrong** [L1cardo/Edge-Helper-uTools#3]
Em……虽然图标地址本身不固定，建议还是至少先获取baseurl再接`\favicon.ico`，比如`url.match('https?:\/\/[^\/]*')[0] + '/favicon.ico'` 其实图标链接应该是存在和书签同一位置的`Favicon`数据库下的，可以尝试将其复制到临时文件夹然后访问提取到实际地址，不过js自身无法访问db们就很麻烦，不知道`utools.browser`有没有什么方法。也尝试了一下使用公共api，比如
```javascript
function getIcon(url) {
  var favicon = 'https://api.iowen.cn/favicon/' + url.match('(?<=:\/\/)[^\/]*')[0] + '.png'
  return favicon
}
```
但是速度并不乐观。

**Comment by ZhangTianrong** [comment]
那啥，我写了个一取消了图标显示的[版本](https://github.com/ZhangTianrong/uToolsEdgeBookmarkSearch)，顺便添加了拼音搜索和目录搜索的功能。想了想，虽然也都是小修小补，但是和你这版有点背道而驰了，所以就另开一个而不发`PR`了。

**Comment by L1cardo** [comment]
@ZhangTianrong 哈哈哈 可以的，js 我也是不会，平时写 swift，这个我还是参考官方的改的
